name: run-tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Type Coverage
        run: vendor/bin/pest --type-coverage --min=100
      - name: Execute tests via Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/pest
